### PR TITLE
Fix friends screen UI problems

### PR DESCRIPTION
**Pull request by MathisHage**
This PR fixes some UI bugs in the friends screen set.

### Changes : 
* Removed erroneous calls to `ProjectTheme`. REMINDER : This method should only be called ONCE and at the root of the app (in `MainActivity.kt`).
* Fixed some texts which where not colored properly (`Leaderboard.kt`, `AddFriends.kt`, `FriendsScreen.kt`).
* Modularization of parts of the code in `Leaderboard.kt`.
* The drop down menus in `Leaderboard.kt` now indicate which item is selected when clicked (the background + text colors change).
* Added some tests for the new code modularization of `Leaderboard.kt`.

Beware : GitHub is wrong about the amount of new code : there is no new addition apart from those mentioned above. The rest was already there. This is due to the removal of `ProjectTheme` calls.

### CODE REVIEW

**Comment by charbelraffoul** [comment]
# Review

This PR thoughtfully addresses the listed points, each enhancing the user interactivity and overall polish of the app. 

- The fixes for improperly colored texts in `Leaderboard.kt`, `AddFriends.kt`, and `FriendsScreen.kt` noticeably improve visual clarity and consistency, which is a significant enhancement to the user experience.
- The modularization of code in `Leaderboard.kt` and the addition of tests demonstrate a commitment to maintainability and reliability, ensuring the codebase is robust for future development.

However, for the dropdown menus in `Leaderboard.kt`, the behavior described ("indicating which item is selected when clicked") is not reflected on my end. The options for "Practice mode" and "Rank metric" are always displayed as they were before (see attached screenshot). If there's a specific change expected here, it might require further clarification or adjustments.
image

Great work overall on improving usability and organization!

**Review by charbelraffoul — CHANGES_REQUESTED** [review]
# Review

This PR thoughtfully addresses the listed points, each enhancing the user interactivity and overall polish of the app.

- The fixes for improperly colored texts in `Leaderboard.kt`, `AddFriends.kt`, and `FriendsScreen.kt` noticeably improve visual clarity and consistency, which is a significant enhancement to the user experience.
- The modularization of code in `Leaderboard.kt` and the addition of tests demonstrate a commitment to maintainability and reliability, ensuring the codebase is robust for future development.

However, for the dropdown menus in `Leaderboard.kt`, the behavior described ("indicating which item is selected when clicked") is not fully clear in the current implementation. The options for "Practice mode" and "Rank metric" are displayed, but the selected metric does not stand out as clearly as expected (see attached screenshot).

image

Currently, the selected metric does not stand out visually or is not immediately apparent at first glance. I only noticed the functionality after reviewing your code and paying close attention to find it. For instance, we could consider displaying the selected metric (e.g., "Success ratio" or "Improvement") instead of the "Rank metric" text. What do you think about this suggestion? I believe it could further improve the user experience and make the selection more intuitive.

Great work overall on improving usability and organization!
Thanks for your efforts!

**Comment by MathisHage** [comment]
Hey, @charbelraffoul, thanks for the suggestion ! Following your request, I changed the background color of the selected item in each drop down menu, and also display the name of the selected item when the drop down menu is unfocused.

**Review by charbelraffoul — APPROVED** [review]
Hey @MathisHage,

Thanks a lot for taking my suggestion into account and improving the UI by dynamically updating the chosen metric and practice mode! The changes to the dropdown menu make the selection process much clearer and more intuitive for users.

I appreciate the effort you’ve put into refining these aspects of the app. Everything looks great now, and I’m happy to approve this PR.

Great job, and thanks again for your dedication to enhancing the user experience!

**Pull request merged**
